# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    ./deploy.ps1

# Archival tasks should always run, regardless of prior failure.
- powershell: |
    mkdir logs
    cp C:\ProgramData\chocolatey\logs\chocolatey.log logs
  condition: always()

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'logs'
    targetPath: 'logs'
  condition: always()
